# -*- coding: utf-8 -*-
"""numpy_ornekleri_2024.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L2dcfzQzbMcDbGqG_WUgyW2k1sOYj6zT
"""

import numpy as np
np.array([1,2,3])
a=np.array([1,2,3])
dizi=np.array([1,2,3,3.14])
dizi
dizi=np.array([1,2,3,3,14],dtype=int)
dizi

"""1) 1,2,3,4,5 Liste"""

result=np.array([1,2,3,4,5])
result

"""2) 1,15 arası otomatik oluşturma"""

result=np.arange(1,16)
result

"""3)50-100 arası 5 er 5 er artacak dizi"""

result=np.arange(50,101,5)
result

import numpy as np

py_list = [1,2,3,4,5,6,7,8,9]

np_array = np.array([1,2,3,4,5,6,7,8,9]) # assign the array to np_array

print(type(py_list))
print(type(np_array))

py_multi = [[1,2,3],[4,5,6],[7,8,9]]
np_multi = np.array(py_multi)

print(py_list)
print(np_multi)

print(np_array.ndim)
print(np_multi.ndim)

print(np_array.shape)
print(np_multi.shape)
